@startuml
skinparam linetype ortho

[GitHub Actions] as ci
[Yandex Object Storage] as s3
[GitHub Secrets] as secrets
[Terraform] as tf

secrets --> ci : TF_VAR_*, AWS_*
ci --> tf : Переменные окружения
tf --> s3 : Чтение/запись tfstate
s3 --> tf : Состояние (tfstate)
tf --> ci : Выход (plan)

note right of s3
  Бакет: mihailenko.a1-backet
  Ключи: dev/vm.tfstate
end note

note left of secrets
  Хранит:
  - YC_TOKEN
  - YC_ACCESS_KEY
  - YC_SECRET_KEY
  - YC_SUBNET_ID
  - SSH_PUBLIC_KEY
end note

@enduml
